[project]
name = "meteo-claire"
version = "1.0.0"
description = "Un tableau de bord météo en français pour consulter la météo d’une ville dans une interface web soignée."
requires-python = ">=3.12"
authors = [
    { name = "THEKUNPRIME", email = "nsanakristy@gmail.com" }
]
dependencies = [
    "flet",
    "httpx"
]

[dependency-groups]
dev = [
    "flet-cli",
    "flet-desktop",
    "flet-web"
]

[tool.flet.metadata]
title = "Météo Claire"

[tool.flet]
org = "dev.flet"
company = "THEKUNPRIME"
copyright = "Copyright (C) 2026 by THEKUNPRIME"

[tool.flet.app]
path = "src"
